### ISSUE TITLE
Implement automatic reset of Moodle instances

### ISSUE THREAD

**Issue by geoffreyvanwyk** [geoffreyvanwyk/learningsandbox.online#7]
The automatic reset needs to take place every hour. Originally the intention was to do the reset on the hour. The reset will be performed from GitHub Actions. GitHub Actions may delay or drop a job at high load times, such as on the hour. (See the note for the `schedule` event: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule). For this reason, the reset should take place 30 minutes past the hour, every hour.

To make the reset instant, a fresh moodledata directory and a fresh database needs to be available at all times for each instance. The reset is then performed by a cron script triggering an Ansible playbook that updates config.php to point to the new directory and database. Thereafter, a new moodledata directory and database needs to be created again for the next switch. The old ones need to be deleted.

### Update to Moodle playbook

- [x] After installation of a Moodle instance, copy the moodledata directory.
- [x] After installation of a Moodle instance, copy the database.
- [x] Create GitHub Actions workflow for running Reset Playbook every hour.

### Tasks for Reset playbook

- [x] Rename current moodledata to old.
- [x] Rename fresh moodledata to current.
- [x] Rename "current" database to old.
- [x] Rename next database to "current.
- [x] Remove old moodledata.
- [x] Drop the old database.
- [x] Extract fresh moodledata.
- [x] Copy next database.
